name: Hello World Workflow

# Trigger the workflow on push to the main branch
on:
  push:
    branches:
      - main

# Define the job that will be executed
jobs:
  say-hello:
    runs-on: ubuntu-latest  # Use an Ubuntu runner

    steps:
      # Step 1: Check out the code from the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Print a Hello message
      - name: Say Hello
        run: echo "Hello, GitHub Actions!"
